"""
services/pdf_export_service.py
Generates professional PDF diagnosis reports from Founder AI analysis output.
Allows founders to share diagnosis with co-founders, advisors, and investors.
"""
import os
import time
import re
from fpdf import FPDF


class DiagnosisReportPDF(FPDF):
    """Custom PDF with Founder AI branding."""

    def header(self):
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(26, 122, 60)  # #1a7a3c
        self.cell(0, 8, "Founder AI — Diagnosis Report", align="L")
        self.set_font("Helvetica", "", 8)
        self.set_text_color(100, 116, 139)
        self.cell(0, 8, time.strftime("%B %d, %Y"), align="R", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(204, 235, 215)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(148, 163, 184)
        self.cell(0, 10, f"Founder Frameworks Lab  •  Page {self.page_no()}/{{nb}}", align="C")


def export_diagnosis_pdf(
    diagnosis_text: str,
    company_name: str = "Your Company",
    framework_used: str = "",
    query: str = "",
    output_dir: str = "exports",
) -> str:
    """
    Generates a PDF report from diagnosis markdown text.
    Returns the file path of the generated PDF.
    """
    os.makedirs(output_dir, exist_ok=True)
    timestamp = time.strftime("%Y%m%d_%H%M%S")
    filename = f"Founder_AI_Diagnosis_{timestamp}.pdf"
    filepath = os.path.join(output_dir, filename)

    pdf = DiagnosisReportPDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)

    # Title
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(15, 35, 24)
    pdf.cell(0, 10, f"Business Diagnosis: {company_name}", new_x="LMARGIN", new_y="NEXT")

    # Metadata
    if framework_used:
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(26, 122, 60)
        pdf.cell(0, 6, f"Framework: {framework_used}", new_x="LMARGIN", new_y="NEXT")

    if query:
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(100, 116, 139)
        pdf.multi_cell(0, 5, f"Challenge: {query[:200]}")
        pdf.ln(4)

    # Separator
    pdf.set_draw_color(26, 122, 60)
    pdf.set_line_width(0.5)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    # Parse and render diagnosis sections
    lines = diagnosis_text.split("\n")
    for line in lines:
        stripped = line.strip()

        # Section headers (## 1. Framework Selected)
        if stripped.startswith("## "):
            pdf.ln(4)
            pdf.set_font("Helvetica", "B", 12)
            pdf.set_text_color(26, 122, 60)
            header_text = stripped.lstrip("# ").strip()
            pdf.cell(0, 8, header_text, new_x="LMARGIN", new_y="NEXT")
            pdf.set_draw_color(204, 235, 215)
            pdf.line(10, pdf.get_y(), 200, pdf.get_y())
            pdf.ln(2)

        # Sub-headers (### or bold items)
        elif stripped.startswith("### "):
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(45, 69, 54)
            pdf.cell(0, 7, stripped.lstrip("# ").strip(), new_x="LMARGIN", new_y="NEXT")

        # Numbered list items (1. Do X)
        elif re.match(r"^\d+[\.\)]\s+", stripped):
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(15, 35, 24)
            pdf.multi_cell(0, 5, f"  {stripped}")
            pdf.ln(1)

        # Bullet points (- item)
        elif stripped.startswith("- ") or stripped.startswith("* "):
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(45, 69, 54)
            bullet_text = stripped.lstrip("-* ").strip()
            pdf.multi_cell(0, 5, f"  • {bullet_text}")

        # Bold text (**text**)
        elif "**" in stripped:
            clean = stripped.replace("**", "")
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(15, 35, 24)
            pdf.multi_cell(0, 5, clean)

        # Regular body text
        elif stripped:
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(45, 69, 54)
            pdf.multi_cell(0, 5, stripped)

        # Blank lines
        else:
            pdf.ln(2)

    # Footer disclaimer
    pdf.ln(10)
    pdf.set_draw_color(204, 235, 215)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 7)
    pdf.set_text_color(148, 163, 184)
    pdf.multi_cell(0, 4,
        "This report was generated by Founder AI using proprietary Founder Frameworks. "
        "All analysis is evidence-based and powered by local AI reasoning. "
        "Data remains private on your device. www.founderframeworkslab.com"
    )

    pdf.output(filepath)
    return filepath
